spring:
  application:
    name: API-Gateway
  redis:
    cluster:
      nodes:
      - 127.0.0.1:6001
      - 127.0.0.1:6002
      - 127.0.0.1:6003
      - 127.0.0.1:6004
      - 127.0.0.1:6005
      - 127.0.0.1:6006
      
server:
  port: 8090
  
logging:
  level:
     org.springframework.cloud.gateway: DEBUG
     reactor.netty.http.client: DEBUG
     
consul:
   url: http://localhost:8500
   path: API-Gateway/
   
routing-path:
   prefix: services

#management:
#  metrics:
#    export:
#      newrelic:
#        api-key: cffe26fd22af853c03a3cf9edb015fc5FFFFNRAL
#        account-id: 1422919
#        step: 5s

amazon :
    s3 :
     endpoint : https://jwr-pub-keys-nonprod.s3.ap-south-1.amazonaws.com

jwt-auth :
      expiration-time : 30 #in days
      enabled : true #added to disabled it for local testing
      
