spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
      - id : raf
        uri : http://localhost:8080
        predicates:
        - Path=/raf/**
        filters:
        - RewritePath=/raf(?<segment>/?.*), $\{segment}
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
  redis:
    cluster:
      nodes:
      - 127.0.0.1:6001
      - 127.0.0.1:6002
      - 127.0.0.1:6003
      - 127.0.0.1:6004
      - 127.0.0.1:6005
      - 127.0.0.1:6006
      
server:
  port: 8090
  

logging:
  level:
     org.springframework.cloud.gateway: DEBUG
     reactor.netty.http.client: DEBUG
