spring:
  application:
    name: API-Gateway
  redis:
    cluster:
      nodes:
      - 127.0.0.1:6001
      - 127.0.0.1:6002
      - 127.0.0.1:6003
      - 127.0.0.1:6004
      - 127.0.0.1:6005
      - 127.0.0.1:6006
      
server:
  port: 8090
  
logging:
  level:
     org.springframework.cloud.gateway: DEBUG
     reactor.netty.http.client: DEBUG
     
consul:
   url: http://localhost:8500
   path: API-Gateway/
   
routing-path:
   prefix: services