spring:
  application:
    name: API-Gateway
      
server:
  port: 8090
  
logging:
  level:
     org.springframework.cloud.gateway: DEBUG
     reactor.netty.http.client: DEBUG
     
consul:
   host: localhost
   port: 8500
   path: API-Gateway/
   token: null
   
routing-path:
   prefix: services

newrelic :
  api-key: rM7ES1W-gTor6sTD4rR0YBnZ1FxmEEFP
  uri: https://metric-api.newrelic.com/metric/v1
  step: 5

amazon :
    s3 :
     endpoint : https://jwr-pub-keys-nonprod.s3.ap-south-1.amazonaws.com

jwt-auth :
      expiration-time : 30 #in days
      disabled : false #added to disabled it for local testing
      
